package kr.goodneighbors.cms.service.model

import android.arch.persistence.room.Ignore

data class ProfileViewItem(
        var CHILD_NAME: String? = null,
        var CHILD_CODE: String? = null,
        var CHRCP_NO: String? = null,
        var RCP_NO: String? = null,
        var RPT_DVCD: String? = null,
        var YEAR: String? = null,
        var RPT_STCD: String? = null,
        var APRV_DT: String? = null,
        var REG_DT: Long? = null,
        var DROP_RCP_NO: String? = null,
        var DROP_RPT_STCD: String? = null,
        var DROPOUT_REMRK_ENG: String? = null,
        var CH_STCD: String? = null,
        var ORG_CHRCP_NO: String? = null,
        var BF_CHRCP_NO: String? = null,
        var BF_CHILD_CODE: String? = null,
        var GNDR: String? = null,
        var BDAY: String? = null,
        var VLG_CD: String? = null,
        var HS_ADDR: String? = null,
        var HS_ADDR_DTL: String? = null,
        var TEL_NO: String? = null,
        var AGE: String? = null,
        var SCTP_CD: String? = null,
        var SCHL_CD: String? = null,
        var GRAD: String? = null,
        var BMI_CD: String? = null,
        var DISB_CD: String? = null,
        var ILNS_CD: String? = null,
        var FA_LTYN: String? = null,
        var MO_LTYN: String? = null,
        var EBRO_LTNUM: String? = null,
        var YBRO_LTNUM: String? = null,
        var ESIS_LTNUM: String? = null,
        var YSIS_LTNUM: String? = null,
        var MGDN_CD: String? = null,
        var MGDN_NM: String? = null,
        var PLAN_YN: String? = null,
        var FTPLN_CD: String? = null,
        var FTPLN_DTL: String? = null,
        var CTNSPN_RNCD: String? = null,
        var CTNSPN_DTL: String? = null,
        var REMRK_ENG: String? = null,
        var DROP_RNCD: String? = null,
        var VLG_NM: String? = null,
        var VLG_LAT: String? = null,
        var VLG_LONG: String? = null,
        var CASE1: String? = null,
        var CASE2: String? = null,
        var CASE3: String? = null,
        var SIBLING1: String? = null,
        var SIBLING2: String? = null,
        var CIF_APRV_DT: String? = null,
        var RPT_STNM: String? = null,
        var SCTP_NM: String? = null,
        var SCHL_NM: String? = null,
        var BMI_NM: String? = null,
        var DISB_NM: String? = null,
        var MGDN_CD_NM: String? = null,
        var ILNS_NM: String? = null,
        var FTPLN_NM: String? = null,
        var CTNSPN_RNNM: String? = null,
        var DROP_RNNM: String? = null,
        var CASE1_NM: String? = null,
        var CASE2_NM: String? = null,
        var CASE3_NM: String? = null,
        var CH_CUSL_INFO_REG_DT: Long? = null,
        var THUMB_FILE_PATH: String? = null,

        @Ignore var GENERAL_FILE_PATH: List<String>? = null,

        @Ignore var codeInterviewPlace: List<SpinnerOption>? = null,
        @Ignore var codeRelationship: List<SpinnerOption>? = null
)

data class CounselingListItem(
        var CHRCP_NO: String? = null,
        var CRT_TP: String? = null,
        var SEQ_NO: String? = null,
        var SPRCP_NO: String? = null,
        var INTVR_NM: String? = null,
        var INTPLC_CD: String? = null,
        var RSPN_RLCD: String? = null,
        var CUSL_CTS: String? = null,
        var CUSL_DT: String? = null,
        var MNG_OPN: String? = null,
        var CUSL_STCD: String? = null,
        var IMG_FP: String? = null,
        var IMG_NM: String? = null,
        var YYYYMM: String? = null,
        var INTPLC_NM: String? = null,
        var RSPN_RLNM: String? = null,
        var RN: Int? = null,
        var REGR_ID: String ?= null,
        var REG_DT: Long ?= null,

        @Ignore var isSelected: Boolean = false
)

data class NextCounselingIndex(
        var VISIT: String,
        var NEXT_SEQ: String
)